import { useState, type Dispatch } from 'react';
import { AlertBanner, Badge, Button, CapacityBar, Card, MetricCard, PageHeading, SelectField, TextField } from '../../../components/common';
import type { Action, DispatchState } from '../model';
import { exportCsv, PageLink } from '../shared';
const forecast=[{week:'5–11 Oct',fresh:640,style:340,tech:200,chilled:290},{week:'12–18 Oct',fresh:690,style:380,tech:220,chilled:320},{week:'19–25 Oct',fresh:820,style:440,tech:250,chilled:400},{week:'26 Oct–1 Nov',fresh:660,style:350,tech:210,chilled:295}];
export function Capacity({state,dispatch}:{state:DispatchState;dispatch:Dispatch<Action>}) {
  const [depot,setDepot]=useState('Peliyagoda'),[buffer,setBuffer]=useState(false),[shift,setShift]=useState(0),[reeferRequest,setReeferRequest]=useState(0),[ambientRequest,setAmbientRequest]=useState(0),[note,setNote]=useState(''),[agreement,setAgreement]=useState(false),[saved,setSaved]=useState(false);const factor=depot==='Peliyagoda'?1:.45,capacity=depot==='Peliyagoda'?1420:620,reefer=depot==='Peliyagoda'?380:170;
  const rows=forecast.map(r=>({...r,fresh:Math.round(r.fresh*factor),style:Math.round(r.style*factor),tech:Math.round(r.tech*factor),chilled:Math.round(r.chilled*factor)}));const peak=Math.max(...rows.map(r=>r.fresh+r.style+r.tech));
  return <><PageHeading eyebrow="Forward planning" title="Capacity planning" description="Compare forecast demand with available fleet capacity over the next four weeks." actions={<SelectField label="Depot" value={depot} onChange={e=>{setDepot(e.target.value);setBuffer(false);setShift(0);setReeferRequest(0);setAmbientRequest(0);setNote('');setAgreement(false);setSaved(false);}}><option>Peliyagoda</option><option>Kandy</option></SelectField>}/><div className="wp-metrics-grid"><MetricCard label="Available fleet" value={depot==='Peliyagoda'?52:24} detail={depot==='Peliyagoda'?'60 total · 8 in maintenance':'28 total · 4 in maintenance'}/><MetricCard label="Volume capacity" value={<>{capacity.toLocaleString()} <small>m³</small></>} detail="Standard dispatch-cycle capacity · demo estimate"/><MetricCard label="Peak forecast" value={<>{peak.toLocaleString()} <small>m³</small></>} badge={<Badge tone="warning">Over capacity</Badge>} detail={`${peak-capacity} m³ above standard capacity`}/></div>
    <Card><div className="wp-card-heading"><div><h2>Weekly demand forecast</h2><p className="wp-description">Illustrative volumes for {depot}. Chilled volume is part of Fresh, not an additional category.</p></div><Badge tone="neutral">4-week horizon</Badge></div><div className="dp-legend"><span><i className="dp-fresh"/>Fresh</span><span><i className="dp-style"/>Style</span><span><i className="dp-tech"/>Tech</span></div><div className="dp-forecasts">{rows.map(r=>{const total=r.fresh+r.style+r.tech;return <article className={`dp-forecast ${total>capacity?'dp-forecast-warning':''}`} key={r.week}><div className="wp-card-heading"><h3>{r.week} 2026</h3><Badge tone={total>capacity?'warning':'success'}>{total.toLocaleString()} m³ · {Math.round(total/capacity*100)}% capacity</Badge></div><div className="dp-chart" role="img" aria-label={`Fresh ${r.fresh}, Style ${r.style}, Tech ${r.tech} cubic metres. Total ${total}; capacity ${capacity}.`}><span className="dp-fresh" style={{width:`${r.fresh/peak*100}%`}}/><span className="dp-style" style={{width:`${r.style/peak*100}%`}}/><span className="dp-tech" style={{width:`${r.tech/peak*100}%`}}/><i className="dp-ceiling" style={{left:`${capacity/peak*100}%`}}/></div><p className="dp-muted">Fresh {r.fresh} · Style {r.style} · Tech {r.tech} m³ · Dashed line: capacity</p><CapacityBar label="Chilled capacity" value={r.chilled} maximum={reefer} unit="m³" tone={r.chilled>reefer?'warning':'info'}/>{total>capacity&&<p className="dp-warning">{total-capacity} m³ above fleet capacity · {Math.max(0,r.chilled-reefer)} m³ chilled shortfall</p>}</article>;})}</div></Card>
    <AlertBanner tone="warning" title="Forecast shortfall requires a dispatcher decision" action={<Button variant="secondary" onClick={()=>setBuffer(true)}>Plan capacity actions</Button>}>The forecast does not allocate vehicles or defer orders automatically. Compare an adjustment, then save your proposed actions for review.</AlertBanner>
    {state.capacityPlans[depot]&&<AlertBanner tone="info" title={`Saved action plan · ${depot}`}>{state.capacityPlans[depot].shift} m³ ambient demand proposed for the preceding week · {state.capacityPlans[depot].reefer} m³ refrigerated and {state.capacityPlans[depot].ambient} m³ ambient capacity requested. Not reserved or confirmed. {state.capacityPlans[depot].note}</AlertBanner>}
    {buffer&&<Card><h2>Plan actions for 19–25 October</h2><p className="wp-description">Compare weekly volume estimates. Only Style/Tech demand can move earlier here. Fresh daily deliveries remain in their requested week.</p><div className="dp-form-stack">
      <TextField label="Move Style/Tech demand to 12–18 October (m³)" type="number" min={0} max={Math.min(100,capacity-(rows[1].fresh+rows[1].style+rows[1].tech))} value={shift} onChange={e=>{setShift(Number(e.target.value));setSaved(false);}} hint="Needs agreement with the affected outlets and validation of their delivery windows."/>
      <TextField label="Additional refrigerated weekly capacity requested (m³)" type="number" min={0} max={200} value={reeferRequest} onChange={e=>{setReeferRequest(Number(e.target.value));setSaved(false);}} hint="Check available vehicles at this depot, spare second trips and remaining fuel. No vehicle is reserved here."/>
      <TextField label="Additional ambient weekly capacity requested (m³)" type="number" min={0} max={200} value={ambientRequest} onChange={e=>{setAmbientRequest(Number(e.target.value));setSaved(false);}}/>
    </div>
    <div className="dp-load-grid"><div><strong>{Math.max(0,peak-shift-capacity-reeferRequest-ambientRequest)} m³</strong><p className="dp-muted">Projected total shortfall after proposed actions</p></div><div><strong>{Math.max(0,rows[2].chilled-reefer-reeferRequest)} m³</strong><p className="dp-muted">Projected chilled shortfall</p></div><div><strong>{rows[1].fresh+rows[1].style+rows[1].tech+shift} / {capacity} m³</strong><p className="dp-muted">Preceding week demand / capacity</p></div></div>
    <p className="wp-description">Refrigerated capacity can carry ambient goods, but ambient capacity cannot cover a chilled shortage. Existing drivers follow their vehicles; no separate driver shortage is assumed. Vehicle availability, two-trip limits, fuel and windows still need validation before any plan is published.</p>
    {shift>0&&<label className="dp-checkbox"><input type="checkbox" checked={agreement} onChange={e=>{setAgreement(e.target.checked);setSaved(false);}}/>Outlet agreement obtained for earlier Style/Tech deliveries</label>}
    <TextField label="Dispatcher action plan" value={note} onChange={e=>{setNote(e.target.value);setSaved(false);}} hint="Record what should be reviewed, by whom, and how any remaining shortage will be handled (10+ characters)."/>
    <div className="wp-demo-row"><Button disabled={note.trim().length<10||(shift>0&&!agreement)||![shift,reeferRequest,ambientRequest].every(n=>Number.isFinite(n)&&n>=0)||shift>Math.min(100,capacity-(rows[1].fresh+rows[1].style+rows[1].tech))||reeferRequest>200||ambientRequest>200} onClick={()=>{dispatch({type:'capacity',depot,agreed:agreement,plan:{shift,reefer:reeferRequest,ambient:ambientRequest,note}});setSaved(true);}}>Save proposed actions</Button><PageLink to="allocation" secondary>Review current allocation</PageLink></div>
    {saved&&<AlertBanner tone="success" title="Capacity action plan saved in this demo">Forecast demand is unchanged. No orders were moved and no vehicles or extra trips were booked.</AlertBanner>}
    </Card>}
    <div className="wp-actions"><Button variant="secondary" onClick={()=>exportCsv(`capacity-${depot.toLowerCase()}.csv`,[['Week','Fresh m3','Style m3','Tech m3','Chilled m3','Capacity m3'],...rows.map(r=>[r.week,r.fresh,r.style,r.tech,r.chilled,capacity])])}>Export capacity CSV</Button></div></>;
}
