import { useEffect, useState, type Dispatch } from 'react';
import { AlertBanner, Badge, Button, CapacityBar, Card, EmptyState, MetricCard, PageHeading, SelectField, TextField } from '../../../components/common';
import { request } from '../../../api/http';
import { useSync } from '../../../context/SyncContext';
import type { Action, DispatchState } from '../model';
import { exportCsv, PageLink } from '../shared';
type Forecast = { iso_week: number; iso_year: number; estimated_dry_trips: number; estimated_reefer_trips: number; brand_forecasts: { brand: string; total_volume_m3: number; total_weight_kg: number }[] };
export function Capacity({state,dispatch}:{state:DispatchState;dispatch:Dispatch<Action>}) {
  const { workspace } = useSync();
  const [depot,setDepot]=useState(state.depot),[forecast,setForecast]=useState<Forecast|null>(null),[error,setError]=useState(''),[open,setOpen]=useState(false);
  const [reefer,setReefer]=useState(0),[ambient,setAmbient]=useState(0),[note,setNote]=useState('');
  useEffect(()=>{let live=true;setForecast(null);setError('');request<Forecast>(`/forecast/weekly?depot=${encodeURIComponent(depot)}`).then(f=>live&&setForecast(f)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[depot]);
  const fleet=(workspace?.vehicles??[]).filter((v:any)=>v.depot===depot);
  const reeferFleet=fleet.filter((v:any)=>v.temp==='reefer').length,dryFleet=fleet.length-reeferFleet;
  const total=forecast?.brand_forecasts.reduce((a,b)=>a+b.total_volume_m3,0)??0;
  const saved=state.capacityPlans[depot];
  const reeferShort=forecast?Math.max(0,forecast.estimated_reefer_trips-reeferFleet*2):0,dryShort=forecast?Math.max(0,forecast.estimated_dry_trips-(dryFleet+reeferFleet)*2+forecast.estimated_reefer_trips-reeferFleet*2):0;
  return <><PageHeading eyebrow="Forward planning" title="Capacity planning" description="Compare the forecast weekly demand with the vehicles and trips this depot has." actions={<SelectField label="Depot" value={depot} onChange={e=>{setDepot(e.target.value);setOpen(false);}}><option>Peliyagoda</option><option>Kandy</option></SelectField>}/>
    {error&&<AlertBanner tone="danger" title="Forecast unavailable">{error}</AlertBanner>}
    {!forecast&&!error&&<EmptyState title="Loading forecast" description="Fetching the weekly demand forecast."/>}
    {forecast&&<><div className="wp-metrics-grid"><MetricCard label="Fleet" value={fleet.length} detail={`${reeferFleet} refrigerated · ${dryFleet} ambient · two trips per vehicle per day`}/><MetricCard label={`Forecast demand · week ${forecast.iso_week}`} value={<>{total.toLocaleString(undefined,{maximumFractionDigits:0})} <small>m³</small></>} detail="Whole-week order volume, all brands"/><MetricCard label="Estimated trips" value={forecast.estimated_dry_trips+forecast.estimated_reefer_trips} badge={<Badge tone={reeferShort||dryShort?'warning':'success'}>{reeferShort||dryShort?'Above fleet trips':'Within fleet'}</Badge>} detail={`${forecast.estimated_reefer_trips} refrigerated · ${forecast.estimated_dry_trips} ambient`}/></div>
    <Card><div className="wp-card-heading"><div><h2>Forecast by brand</h2><p className="wp-description">Planning estimate from order history. It does not allocate vehicles or defer orders.</p></div><Badge tone="neutral">Week {forecast.iso_week}, {forecast.iso_year}</Badge></div>{forecast.brand_forecasts.map(b=><CapacityBar key={b.brand} label={`${b.brand} · ${Math.round(b.total_weight_kg).toLocaleString()} kg`} value={Math.round(b.total_volume_m3)} maximum={Math.max(1,Math.round(total))} unit="m³"/>)}</Card>
    <AlertBanner tone={reeferShort||dryShort?'warning':'info'} title={reeferShort||dryShort?`Forecast needs about ${reeferShort} more refrigerated and ${dryShort} more ambient trips than the fleet offers`:'Forecast fits the fleet'} action={<Button variant="secondary" onClick={()=>setOpen(true)}>Plan capacity actions</Button>}>Record what should be reviewed. Nothing is reserved or booked from this page.</AlertBanner></>}
    {saved&&<AlertBanner tone="info" title={`Saved action plan · ${depot}`}>{saved.reefer} refrigerated and {saved.ambient} ambient extra trips requested. Not reserved or confirmed. {saved.note}</AlertBanner>}
    {open&&<Card><h2>Capacity actions for {depot}</h2><div className="dp-form-stack"><TextField label="Additional refrigerated trips requested per week" type="number" min={0} max={200} value={reefer} onChange={e=>setReefer(Number(e.target.value))} hint="Check spare vehicles, second trips and remaining fuel quota. No vehicle is reserved here."/><TextField label="Additional ambient trips requested per week" type="number" min={0} max={200} value={ambient} onChange={e=>setAmbient(Number(e.target.value))}/><TextField label="Dispatcher action plan" value={note} onChange={e=>setNote(e.target.value)} hint="Record who reviews this and how a remaining shortage is handled (10+ characters)."/></div><div className="wp-demo-row"><Button disabled={note.trim().length<10||![reefer,ambient].every(n=>Number.isFinite(n)&&n>=0&&n<=200)} onClick={()=>{dispatch({type:'capacity',depot,agreed:true,plan:{shift:0,reefer,ambient,note}});setOpen(false);}}>Save proposed actions</Button><PageLink to="allocation" secondary>Review current allocation</PageLink></div></Card>}
    {forecast&&<div className="wp-actions"><Button variant="secondary" onClick={()=>exportCsv(`capacity-${depot.toLowerCase()}.csv`,[['Brand','Volume m3','Weight kg'],...forecast.brand_forecasts.map(b=>[b.brand,b.total_volume_m3,b.total_weight_kg])])}>Export forecast CSV</Button></div>}</>;
}
