import { Badge, Card, MetricCard, PageHeading } from '../../../components/common';
import { deferred, planWarnings, trips, type DispatchState } from '../model';
import { PageLink, path } from '../shared';
export function Home({state:s}:{state:DispatchState}) {
  const warnings=planWarnings(s);const repeated=s.orders.filter(o=>o.skips>0&&(!s.generated||!o.trip));const alertCount=Number(!s.issueResolved)+warnings.length+Number(repeated.length>0&&!s.recorded);
  const stages=[{title:'Order queue',detail:s.closed?'Queue locked for planning':'Review orders before the 16:00 cutoff',to:'orders',status:s.closed?'Complete':'Active'}, {title:'Capacity & plan',detail:s.generated?'Review trip assignments and constraints':'Allocate orders to available vehicles',to:'allocation',status:s.confirmed?'Complete':s.generated?'Active':'Pending'}, {title:'Deferral review',detail:s.recorded?'Reasons recorded for all deferred orders':'Review previous skips and next delivery dates',to:'deferrals',status:s.recorded?'Complete':s.generated?'Needs review':'Pending'}, {title:'Fleet tracking',detail:'Follow deliveries and resolve incidents',to:'tracking',status:'Active'}];
  return <><PageHeading eyebrow="Peliyagoda · Dispatch operations" title="Today’s fulfilment & dispatch" description="Monday, 5 October 2026 · Demo delivery day" actions={<><Badge tone={s.closed?'neutral':'warning'}>{s.closed?'Queue closed':'Queue cutoff · 16:00 LK'}</Badge><PageLink to="orders">Go to order queue →</PageLink></>} />
    <div className="wp-metrics-grid"><MetricCard label="Confirmed orders" value={s.orders.length} detail={`${s.orders.filter(o=>o.temp==='Ambient').length} ambient · ${s.orders.filter(o=>o.temp==='Chilled').length} chilled`} /><MetricCard label="Fleet available" value={<>4 <small>/ 5</small></>} badge={<Badge tone="success">80% available</Badge>} detail="1 vehicle in maintenance · 3 trucks and 1 van available" /><MetricCard label="Requiring attention" value={alertCount} badge={<Badge tone={alertCount?'warning':'success'}>{alertCount?'Action required':'All clear'}</Badge>} detail="Access constraints, repeated deferrals and delivery incidents" /></div>
    <Card><div className="wp-card-heading"><h2>Dispatch workflow</h2><Badge tone="info">{s.confirmed?'Plan confirmed':s.generated?'Planning & review':'Order intake'}</Badge></div><ol className="dp-workflow">{stages.map((stage,i)=><li key={stage.to}><a href={path(stage.to)}><span className="dp-step">{i+1}</span><Badge tone={stage.status==='Complete'?'success':stage.status==='Active'?'info':'neutral'}>{stage.status}</Badge><h3>{stage.title}</h3><p>{stage.detail}</p></a></li>)}</ol></Card>
    <div className="wp-card-heading"><h2>Priority alerts</h2><span className="wp-description">Review the next action for each exception</span></div>
    {!s.recorded&&repeated.length>0&&<Card className="dp-alert-card"><div><Badge tone="warning">Repeated deferral risk</Badge><h3>{repeated[0].outlet} · {repeated[0].name}</h3><p>Skipped {repeated[0].skips} previous runs. Review this order before confirming the next plan.</p></div><PageLink secondary to={s.generated?'deferrals':'orders?priority=1'}>Review priority orders</PageLink></Card>}
    {warnings.map(w=><Card key={w.order.id} className="dp-alert-card"><div><Badge tone="danger">{w.reason}</Badge><h3>{w.order.name}</h3><p>This stop needs a compatible vehicle before the plan can be confirmed.</p></div><PageLink to="allocation" secondary>Review assignment</PageLink></Card>)}
    {!s.issueResolved&&<Card className="dp-alert-card"><div><Badge tone="danger">Delivery issue · morning run</Badge><h3>VEH014 · Loading bay access blocked</h3><p>The driver is waiting for instructions at Kollupitiya. Review the incident and record the action taken.</p></div><PageLink to="trip/TRP-0842" secondary>Resolve issue</PageLink></Card>}
    <Card className="dp-summary-strip"><span><strong>{s.generated?s.orders.length-deferred(s).length:0}</strong> orders allocated</span><span><strong>{s.generated?deferred(s).length:0}</strong> proposed deferrals</span><span><strong>{trips.length}</strong> available trips</span></Card>
    {s.audit.length>0&&<Card><h2>Dispatcher decision history</h2><ol className="dp-info-log">{s.audit.map((entry,index)=><li key={index}>{entry}</li>)}</ol></Card>}
  </>;
}
