import { useState, type Dispatch } from 'react';
import { AlertBanner, Badge, Button, Card, EmptyState, Modal, PageHeading, Pagination, SelectField, TextField } from '../../../components/common';
import type { Action, DispatchState, Order } from '../model';
import { DeferModal } from './Planning';
import { exportCsv, PageLink, Table } from '../shared';
export function OrderQueue({state:s,dispatch,priorityOnly=false}:{state:DispatchState;dispatch:Dispatch<Action>;priorityOnly?:boolean}) {
  const [search,setSearch]=useState(''),[district,setDistrict]=useState('all'),[temp,setTemp]=useState('all'),[sort,setSort]=useState(priorityOnly?'skips':'priority'),[page,setPage]=useState(1),[closing,setClosing]=useState(false),[selected,setSelected]=useState<Order|null>(null),[deferOrder,setDeferOrder]=useState<Order|null>(null);
  const rows=s.orders.filter(o=>(o.id+' '+o.outlet+' '+o.name).toLowerCase().includes(search.toLowerCase())&&(district==='all'||o.district===district)&&(temp==='all'||o.temp===temp)).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='skips'?b.skips-a.skips:Number(b.priority)-Number(a.priority)||b.skips-a.skips);
  const change=(fn:()=>void)=>{fn();setPage(1);};
  return <><PageHeading eyebrow="Order intake" title="Order queue" description="Review confirmed orders and prioritise outlets before locking the queue." actions={<Badge tone={s.closed?'neutral':'success'}>{s.closed?'Closed':'Open'} · {s.orders.length} orders</Badge>} />
    <Card className="dp-alert-card"><div><h2>{s.closed?'Queue locked':'Queue cutoff · 16:00 LK'}</h2><p>{s.closed?'Priorities are locked. Continue to the allocation plan.':'Close the demo queue when your review is complete. This freezes priorities for planning.'}</p></div><div className="wp-actions"><Button variant="secondary" onClick={()=>exportCsv('order-queue.csv',[['Order','Outlet','District','Temperature','Weight kg','Priority'],...rows.map(o=>[o.id,o.name,o.district,o.temp,o.kg,o.priority?'Yes':'No'])])}>Export CSV</Button>{s.closed?<PageLink to="allocation">Continue to plan →</PageLink>:<Button onClick={()=>setClosing(true)}>Close queue & lock</Button>}</div></Card>
    <Card className="wp-table-card"><div className="dp-filters"><TextField label="Search orders" placeholder="Order ID, outlet or name" type="search" value={search} onChange={e=>change(()=>setSearch(e.target.value))}/><SelectField label="District" value={district} onChange={e=>change(()=>setDistrict(e.target.value))}><option value="all">All districts</option><option>Colombo</option><option>Gampaha</option></SelectField><SelectField label="Temperature" value={temp} onChange={e=>change(()=>setTemp(e.target.value))}><option value="all">All regimes</option><option>Chilled</option><option>Ambient</option></SelectField><SelectField label="Sort by" value={sort} onChange={e=>change(()=>setSort(e.target.value))}><option value="priority">Priority first</option><option value="skips">Previous skips</option><option value="name">Outlet name</option></SelectField></div>
    {rows.length?<Table label="Order queue" headings={['Order / outlet','District','Temperature','Load','Previous skips','Actions']}>{rows.slice((page-1)*5,page*5).map(o=><tr key={o.id}><th scope="row">{o.id}<strong className="dp-cell-title">{o.name}</strong><span className="dp-muted">{o.outlet}</span></th><td>{o.district}</td><td><Badge tone={o.temp==='Chilled'?'info':'neutral'}>{o.temp}</Badge>{o.vanOnly&&<p className="dp-muted">Van access only</p>}</td><td>{o.kg} kg<br/>{o.volume} m³</td><td><Badge tone={o.skips?'warning':'neutral'}>{o.skips?`${o.skips} previous runs`:'None'}</Badge></td><td><div className="wp-actions"><Button variant="secondary" onClick={()=>setSelected(o)}>Inspect</Button><Button variant="ghost" disabled={s.closed} aria-pressed={o.priority} aria-label={`Prioritise ${o.id}`} onClick={()=>dispatch({type:'priority',id:o.id})}>{o.priority?'★ Priority':'☆ Prioritise'}</Button>{s.generated&&!s.confirmed&&o.trip&&<Button variant="ghost" onClick={()=>setDeferOrder(o)}>Defer order</Button>}{s.generated&&!o.trip&&<PageLink to="deferrals" secondary>Review deferral</PageLink>}</div></td></tr>)}</Table>:<EmptyState title="No matching orders" description="Try another search or clear the filters." action={<Button variant="secondary" onClick={()=>change(()=>{setSearch('');setDistrict('all');setTemp('all');})}>Clear filters</Button>} />}
    <Pagination page={page} pageSize={5} total={rows.length} onChange={setPage}/></Card>
    <DeferModal key={deferOrder?.id??'closed'} order={deferOrder} dispatch={dispatch} onClose={()=>setDeferOrder(null)}/>
    <Modal open={closing} onClose={()=>setClosing(false)} title="Close the order queue?" description={`${s.orders.length} confirmed orders will be locked for this demo plan.`} footer={<><Button variant="secondary" onClick={()=>setClosing(false)}>Cancel</Button><Button onClick={()=>{dispatch({type:'close'});setClosing(false);}}>Close queue</Button></>}><AlertBanner title="Priorities will become read-only">Review priority outlets first. You can reset the demo to start again.</AlertBanner></Modal>
    <Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?.name??'Order details'} footer={<Button onClick={()=>setSelected(null)}>Done</Button>}>{selected&&<dl className="dp-details"><dt>Order</dt><dd>{selected.id}</dd><dt>Outlet</dt><dd>{selected.outlet}</dd><dt>Temperature</dt><dd>{selected.temp}</dd><dt>Load</dt><dd>{selected.kg} kg · {selected.volume} m³</dd><dt>Access</dt><dd>{selected.vanOnly?'Van only':'Standard access'}</dd><dt>Previous skips</dt><dd>{selected.skips}</dd></dl>}</Modal>
  </>;
}
