import { useState, type Dispatch } from 'react';
import { AlertBanner, Badge, Button, CapacityBar, Card, EmptyState, MetricCard, Modal, PageHeading, SelectField, TextField } from '../../../components/common';
import { canConfirm, canRecord, compatibility, deferred, isReviewed, loadFor, validNextDate, type Action, type DispatchState, type Order } from '../model';
import { PageLink, path, Table } from '../shared';
export function ReassignModal({order,state,onClose,dispatch}:{order:Order|null;state:DispatchState;onClose:()=>void;dispatch:Dispatch<Action>}) {
  const [target,setTarget]=useState('');
  const selected=state.trips.find(t=>t.id===target);
  return <Modal open={!!order} onClose={onClose} title={`Reassign ${order?.outlet??'stop'}`} description="Choose a compatible vehicle and trip. Loads below include this order." footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!order||!selected||selected.id===order.trip||!!compatibility(order,selected,state.orders).length} onClick={()=>{if(order)dispatch({type:'reassign',id:order.id,trip:target});onClose();}}>Apply reassignment</Button></>}>
    {order&&<><p className="dp-inset">{order.id} · {order.kg} kg · {order.volume} m³ · {order.temp}{order.vanOnly?' · Van access required':''}</p><fieldset className="dp-options"><legend>Available trips</legend>{state.trips.filter(t=>t.id!==order.trip&&t.brand===order.brand&&t.district===order.district).map(t=>{const reasons=compatibility(order,t,state.orders);const load=loadFor(state.orders.filter(o=>o.id!==order.id),t.id);return <label className={`dp-option ${target===t.id?'dp-option-selected':''}`} key={t.id}><input type="radio" name="reassign" value={t.id} checked={target===t.id} disabled={!!reasons.length} onChange={()=>setTarget(t.id)}/><span><strong>{t.code}</strong><span className="dp-cell-title">{t.temp} {t.kind.toLowerCase()} · Departure {t.depart} LK</span><span className="dp-muted">After move: {load.kg+order.kg}/{t.kg} kg · {(load.volume+order.volume).toFixed(2)}/{t.volume} m³</span><span className="dp-cell-title"><Badge tone={reasons.length?'warning':'success'}>{reasons.join(' · ')||'Compatible'}</Badge></span></span></label>;})}</fieldset></>}
  </Modal>;
}
export function Allocation({state:s,dispatch,summary=false}:{state:DispatchState;dispatch:Dispatch<Action>;summary?:boolean}) {
  const [reassign,setReassign]=useState<Order|null>(null),[deferOrder,setDeferOrder]=useState<Order|null>(null),[confirm,setConfirm]=useState(false),[filter,setFilter]=useState('all');const warnings=s.warnings;const unassigned=deferred(s);const readOnly=s.confirmed;
  if(!s.generated)return <><PageHeading title="Allocation plan" description="{s.depot} depot · {s.deliveryDate}"/><Card><EmptyState title={s.closed?'Ready to build your plan':'Review the order queue first'} description={s.closed?'Generate a suggested allocation, then choose what to serve, reassign or defer. Previously skipped outlets are considered first.':'Close the queue to lock priorities before generating the plan.'} action={s.closed?<Button onClick={()=>dispatch({type:'generate'})}>Generate plan</Button>:<PageLink to="orders">Review order queue</PageLink>}/></Card></>;
  return <><PageHeading eyebrow={`${s.depot} depot`} title={readOnly?'Confirmed allocation plan':'Allocation plan'} description={`Deliveries for ${s.deliveryDate}`} actions={readOnly?<Badge tone="success">Read-only · Confirmed</Badge>:<Badge tone="info">Draft plan</Badge>}/>
    {readOnly?<AlertBanner tone="success" title="Plan published">Assignments are locked. Loaders, drivers and stores can now see this plan.</AlertBanner>:<AlertBanner tone={warnings.length?'danger':'warning'} title={warnings.length?`${warnings.length} constraint violation(s)`:`${unassigned.length} proposed deferrals`}>{warnings.length?'Resolve incompatible assignments before confirming.':'Record the reasons and next delivery dates before confirming the remaining trips.'}</AlertBanner>}
    <div className="wp-metrics-grid"><MetricCard label="Assigned orders" value={<>{s.orders.length-unassigned.length}<small> / {s.orders.length}</small></>} detail="Orders matched to a trip"/><MetricCard label="Vehicles in use" value={s.trips.length} detail={`${new Set(s.trips.map(t=>t.vehicle)).size} vehicles · ${s.trips.length} trips`}/><MetricCard label="Deferred orders" value={unassigned.length} badge={<Badge tone={s.recorded?'success':'warning'}>{s.recorded?'Decisions recorded':'Proposed · Review'}</Badge>}/></div>
    <div className="wp-card-heading"><h2>Proposed trips</h2><SelectField label="Show trips" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All trips</option><option value="attention">Requires attention</option></SelectField></div>
    {s.trips.filter(t=>filter==='all'||warnings.some(w=>w.order.trip===t.id)).map(t=>{const orders=s.orders.filter(o=>o.trip===t.id),load=loadFor(s.orders,t.id);return <Card key={t.id}><div className="wp-card-heading"><div><h2>{t.vehicle} · {t.temp} {t.kind.toLowerCase()}</h2><p className="wp-description">{t.brand} · trip {t.tripNo} · {t.district} · Departure {t.depart} LK · {orders.length} stops · Estimated fuel {t.fuelL} L</p></div><Badge tone={warnings.some(w=>w.order.trip===t.id)?'danger':'success'}>{warnings.some(w=>w.order.trip===t.id)?'Needs attention':'Compatible'}</Badge></div><div className="dp-load-grid"><CapacityBar label="Weight load" value={load.kg} maximum={t.kg} unit="kg"/><CapacityBar label="Volume" value={load.volume} maximum={t.volume} unit="m³"/><CapacityBar label="Trip time" value={t.minutes} maximum={t.budget} unit="min"/></div>
    <details className="dp-stops" open={warnings.some(w=>w.order.trip===t.id)}><summary>View {orders.length} assigned stops</summary>{orders.length?orders.map(o=><div className="dp-stop-row" key={o.id}><div><strong>{o.outlet} · {o.name}</strong><p className="dp-muted">{o.kg} kg · {o.volume} m³ · ETA {t.stops.find(x=>x.orderUid===o.uid)?.eta??'–'}{warnings.filter(w=>w.order.id===o.id).map(w=>' · '+w.reason).join('')}</p></div>{!readOnly&&<div className="wp-actions"><Button variant="secondary" onClick={()=>setReassign(o)}>Reassign stop</Button><Button variant="ghost" onClick={()=>setDeferOrder(o)}>Defer order</Button></div>}</div>):<p className="wp-description">Standby vehicle. No orders assigned.</p>}</details></Card>;})}
    {filter==='attention'&&!warnings.length&&<EmptyState title="No constraints to resolve" description="All assigned stops match the available vehicle capabilities."/>}
    <Card className="dp-action-bar"><span>{readOnly?'This is the confirmed, read-only plan.':warnings.length?'Resolve access constraints, then review deferrals.':s.recorded?'All checks passed. Ready to publish.':'Record deferral reasons to continue.'}</span><div className="wp-actions">{readOnly?<PageLink to="tracking">Go to live tracking →</PageLink>:<><PageLink to="deferrals" secondary>Review {unassigned.length} deferrals</PageLink><Button disabled={!canConfirm(s)} onClick={()=>setConfirm(true)}>Publish plan</Button></>}</div></Card>
    <DeferModal key={deferOrder?.id??'defer-closed'} order={deferOrder} state={s} dispatch={dispatch} onClose={()=>setDeferOrder(null)}/>
    <ReassignModal key={reassign?.id??'closed'} order={reassign} state={s} onClose={()=>setReassign(null)} dispatch={dispatch}/>
    <Modal open={confirm} onClose={()=>setConfirm(false)} title="Publish this allocation plan?" description="Assignments become read-only and the plan is sent to loaders, drivers and stores." footer={<><Button variant="secondary" onClick={()=>setConfirm(false)}>Cancel</Button><Button onClick={()=>{dispatch({type:'confirm'});setConfirm(false);window.location.hash=path('confirmed');}}>Publish plan</Button></>}><p>{s.orders.length-unassigned.length} orders allocated · {unassigned.length} deferrals recorded.</p><p className="wp-description">The server re-validates every constraint before publishing and refuses an invalid plan.</p></Modal>
  </>;
}
export function DeferModal({order,state,dispatch,onClose}:{order:Order|null;state:DispatchState;dispatch:Dispatch<Action>;onClose:()=>void}) {
  const [reason,setReason]=useState(''),[date,setDate]=useState(state.operatingDates.find(d=>d>state.deliveryDate)??''),[note,setNote]=useState('');
  return <Modal open={!!order} onClose={onClose} title={`Defer ${order?.id??'order'}`} description="This removes the whole order from its draft trip and releases that capacity." footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!reason||!validNextDate(state,date)||note.trim().length<10} onClick={()=>{if(order)dispatch({type:'defer',id:order.id,reason,nextDate:date,note});onClose();}}>Confirm deferral</Button></>}>
    {order&&<><AlertBanner tone="warning" title={`${order.name} · ${order.skips} previous skips`}>This outlet will not receive this order in the current run. Consider a compatible trip before deferring it again.</AlertBanner><div className="dp-form-stack"><SelectField label="Decision reason" value={reason} onChange={e=>setReason(e.target.value)}><option value="">Select reason</option>{['Prioritise another outlet','Fleet capacity','Outlet access restriction','Delivery window','Store-requested change'].map(r=><option key={r}>{r}</option>)}</SelectField><SelectField label="Proposed next operating date" value={date} onChange={e=>setDate(e.target.value)}>{state.operatingDates.filter(d=>d>state.deliveryDate).slice(0,14).map(d=><option key={d}>{d}</option>)}</SelectField><TextField label="Decision and outlet impact" value={note} onChange={e=>setNote(e.target.value)} hint="Record the tradeoff and any store agreement (at least 10 characters)."/></div></>}
  </Modal>;
}
export function Deferrals({state:s,dispatch}:{state:DispatchState;dispatch:Dispatch<Action>}) {
  const [reassign,setReassign]=useState<Order|null>(null);
  const orders=[...deferred(s)].sort((a,b)=>b.skips-a.skips);const complete=orders.filter(o=>isReviewed(s,o)).length;
  if(!s.generated)return <EmptyState title="Generate an allocation first" description="The planner will propose assignments; you decide which unassigned orders to defer." action={<PageLink to="allocation">Go to allocation plan</PageLink>}/>;
  return <><PageHeading title="Review proposed deferrals" description="Unassigned is a suggestion, not a final decision. Try another trip or accept the deferral with its impact recorded." actions={<Badge tone={s.recorded?'success':'warning'}>{complete} / {orders.length} decisions reviewed</Badge>}/>
    {!s.confirmed&&orders.some(o=>!o.reviewed&&o.skips===0&&o.reason)&&<Card className="dp-action-bar"><p>Outlets that were not skipped before can be accepted as the planner proposed. Outlets skipped earlier still need your own note.</p><Button variant="secondary" onClick={()=>orders.filter(o=>!o.reviewed&&o.skips===0&&o.reason&&validNextDate(s,o.nextDate)).forEach(o=>dispatch({type:'review',id:o.id,note:o.decisionNote||`Planner proposal accepted: ${o.reason}`,accepted:true}))}>Accept {orders.filter(o=>!o.reviewed&&o.skips===0&&o.reason).length} planner proposals</Button></Card>}
    {!orders.length&&<EmptyState title="All orders are assigned" description="No deferrals to record. You can still defer an assigned order from the allocation plan." action={<PageLink to="allocation">Review allocation</PageLink>}/>}
    {orders.map(o=><Card key={o.id}><div className="wp-card-heading"><div><h2>{o.name}</h2><p className="wp-description">{o.id} · {o.temp} · {o.kg} kg · {o.volume} m³</p></div><Badge tone={o.skips?'warning':'neutral'}>{o.skips} previous skips</Badge></div>
      <p className="dp-inset">{o.source==='dispatcher'?'Dispatcher decision (recorded)': 'Planner suggestion'}: {o.reason||'Needs review'}</p>
      {o.proposal&&<details className="dp-stops"><summary>Why was no trip selected?</summary><p className="wp-description">{o.proposal}</p><p className="wp-description">This explains the original draft. Use “Try assigning a trip” to check current capacity after changes.</p></details>}
      <div className="dp-form-stack"><SelectField label={`Reason for ${o.id}`} value={o.reason} disabled={s.confirmed} onChange={e=>dispatch({type:'deferral',id:o.id,reason:e.target.value,nextDate:o.nextDate})}><option value="">Select reason</option>{['No compatible trip','Fleet capacity','Refrigeration required','Delivery window','Outlet access restriction','Prioritise another outlet','Store-requested change'].map(r=><option key={r}>{r}</option>)}</SelectField><SelectField label={`Next operating date for ${o.id}`} value={o.nextDate} disabled={s.confirmed} onChange={e=>dispatch({type:'deferral',id:o.id,reason:o.reason,nextDate:e.target.value})}>{s.operatingDates.filter(d=>d>s.deliveryDate).slice(0,14).map(d=><option key={d}>{d}</option>)}</SelectField><TextField label={`Decision note for ${o.id}`} value={o.decisionNote} disabled={s.confirmed} hint={o.skips?'Required: explain why this outlet must be skipped again (10+ characters).':'Record the tradeoff or store agreement.'} onChange={e=>dispatch({type:'review',id:o.id,note:e.target.value,accepted:false})}/></div>
      <div className="dp-action-bar"><label className="dp-checkbox"><input type="checkbox" checked={o.reviewed} disabled={s.confirmed||!o.reason||!validNextDate(s,o.nextDate)||(o.skips>0&&o.decisionNote.trim().length<10)} onChange={e=>dispatch({type:'review',id:o.id,note:o.decisionNote,accepted:e.target.checked})}/>I accept this deferral and its impact</label>{!s.confirmed&&<Button variant="secondary" onClick={()=>setReassign(o)}>Try assigning a trip</Button>}</div>
    </Card>)}
    <Card className="dp-action-bar"><p>The next date is where each order is carried; stores are told about the deferral once it is recorded.</p><div className="wp-actions"><PageLink to="allocation" secondary>Back to allocation</PageLink>{!s.confirmed&&orders.length>0&&<Button disabled={!canRecord(s)} onClick={()=>{dispatch({type:'record'});window.location.hash=path('deferrals-recorded');}}>Record reviewed deferrals</Button>}</div></Card>
    <ReassignModal key={reassign?.id??'restore'} order={reassign} state={s} dispatch={dispatch} onClose={()=>setReassign(null)}/>
  </>;
}
export function Confirmation({state:s,kind}:{state:DispatchState;kind:'plan'|'deferrals'}) {
  const done=kind==='plan'?s.confirmed:s.recorded;
  if(!done)return <EmptyState title="This step is not complete yet" description="Complete the required review before opening its confirmation." action={<PageLink to={kind==='plan'?'allocation':'deferrals'}>Continue review</PageLink>}/>;
  return <div className="dp-confirmation"><span className="dp-confirm-icon" aria-hidden="true">✓</span><h1>{kind==='plan'?'Plan published':'Deferrals recorded'}</h1><p>{kind==='plan'?'The allocation is now read-only and visible to loaders, drivers and stores.':'Deferral reasons and next dates have been saved and are visible to the affected stores.'}</p><Card><dl className="dp-details"><dt>Depot</dt><dd>{s.depot}</dd><dt>Delivery date</dt><dd>{s.deliveryDate}</dd><dt>Allocated orders</dt><dd>{s.orders.length-deferred(s).length}</dd><dt>Deferred orders</dt><dd>{deferred(s).length}</dd></dl></Card><div className="wp-actions"><PageLink to={kind==='plan'?'summary':'allocation'}>{kind==='plan'?'View confirmed plan':'Return to allocation plan'}</PageLink><PageLink to="home" secondary>Back to home</PageLink></div></div>;
}
