import { useState, type Dispatch } from 'react';
import { AlertBanner, Badge, Button, Card, EmptyState, Modal, PageHeading, Pagination, SelectField, TextField } from '../../../components/common';
import { IssueActions } from './IssueActions';
import type { Action, DispatchState } from '../model';
import { exportCsv, PageLink, Table } from '../shared';
const fleet=[
 {id:'TRP-0842',vehicle:'VEH014',driver:'K. Perera',district:'Colombo',destination:'Kollupitiya',done:2,total:5,eta:'06:10',status:'Issue flagged'},
 {id:'TRP-0846',vehicle:'VEH019',driver:'S. Fernando',district:'Kandy',destination:'Peradeniya',done:1,total:4,eta:'07:15',status:'Delayed'},
 {id:'TRP-0847',vehicle:'VEH018',driver:'N. Jayasuriya',district:'Kurunegala',destination:'Kurunegala Hub',done:2,total:3,eta:'07:45',status:'In transit'},
 {id:'TRP-0848',vehicle:'VEH009',driver:'D. Rathnayake',district:'Colombo',destination:'Dehiwala',done:4,total:6,eta:'06:50',status:'In transit'},
 {id:'TRP-0849',vehicle:'VEH045',driver:'T. Silva',district:'Galle',destination:'Galle Fort',done:1,total:4,eta:'08:20',status:'In transit'},
 {id:'TRP-0850',vehicle:'VEH032',driver:'M. Bandara',district:'Gampaha',destination:'Negombo',done:3,total:3,eta:'06:30',status:'Completed'},
];
function statusTone(status:string) { return status==='Issue flagged'?'danger':status==='Delayed'?'warning':status==='Completed'?'success':'info'; }
export function Tracking({state:s}:{state:DispatchState}) {
  const [search,setSearch]=useState(''),[district,setDistrict]=useState('all'),[status,setStatus]=useState('all'),[page,setPage]=useState(1);
  const rows=fleet.map(f=>({...f,status:f.id==='TRP-0842'?(s.issueResolved?'Awaiting driver update':s.issueStatus==='awaiting'?'Awaiting outcome':s.issueStatus==='acknowledged'?'Acknowledged':f.status):f.status})).filter(f=>(`${f.vehicle} ${f.driver} ${f.destination}`).toLowerCase().includes(search.toLowerCase())&&(district==='all'||f.district===district)&&(status==='all'||f.status===status));
  return <><PageHeading eyebrow="Fleet operations" title="Live tracking" description="Demo morning-run snapshot · 5 October, 06:10 LK. Separate from the draft allocation." actions={<Button variant="secondary" onClick={()=>exportCsv('dispatch-log.csv',[['Trip','Vehicle','Driver','District','Status'],...rows.map(r=>[r.id,r.vehicle,r.driver,r.district,r.status])])}>Export dispatch log</Button>}/>
    {!s.issueResolved&&<AlertBanner tone="danger" title="VEH014 · Access blocked at Kollupitiya" action={<PageLink to="trip/TRP-0842">Resolve issue →</PageLink>}>Loading bay repairs are preventing unloading. The driver needs instructions.</AlertBanner>}
    <Card className="wp-table-card"><div className="dp-filters"><TextField label="Search fleet" type="search" placeholder="Vehicle, driver or destination" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><SelectField label="District" value={district} onChange={e=>{setDistrict(e.target.value);setPage(1);}}><option value="all">All districts</option>{[...new Set(fleet.map(f=>f.district))].map(d=><option key={d}>{d}</option>)}</SelectField><SelectField label="Delivery status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All statuses</option>{['In transit','Issue flagged','Acknowledged','Awaiting outcome','Awaiting driver update','Delayed','Completed'].map(d=><option key={d}>{d}</option>)}</SelectField></div>
    {rows.length?<Table label="Fleet tracking" headings={['Vehicle / driver','District','Destination','Stops','ETA (LK)','Status','Action']}>{rows.slice((page-1)*5,page*5).map(f=><tr key={f.id}><th scope="row">{f.vehicle}<span className="dp-cell-title">{f.driver}</span></th><td>{f.district}</td><td>Peliyagoda →<strong className="dp-cell-title">{f.destination}</strong></td><td>{f.done} / {f.total}</td><td>{f.eta}{f.status==='Delayed'&&<p className="dp-muted">+25 min</p>}</td><td><Badge tone={statusTone(f.status)}>{f.status}</Badge></td><td><PageLink to={`trip/${f.id}`} secondary>View trip</PageLink></td></tr>)}</Table>:<EmptyState title="No matching trips" description="Try another district, status or search." action={<Button variant="secondary" onClick={()=>{setSearch('');setDistrict('all');setStatus('all');setPage(1);}}>Clear filters</Button>}/>}
    <Pagination page={page} pageSize={5} total={rows.length} onChange={setPage}/></Card></>;
}
export function TripDetail({id,state:s,dispatch}:{id:string;state:DispatchState;dispatch:Dispatch<Action>}) {
  const trip=fleet.find(f=>f.id===id);
  if(!trip)return <EmptyState title="Trip not found" description="Select an available trip from fleet tracking." action={<PageLink to="tracking">Back to tracking</PageLink>}/>;
  const incident=id==='TRP-0842';const stops=incident?['Borella Fresh','Maradana Market','Kollupitiya Central','Bambalapitiya Fresh','Wellawatte Fresh']:Array.from({length:trip.total},(_,i)=>`${trip.destination} · Outlet ${i+1}`);
  return <><div><PageLink to="tracking" secondary>← Back to tracking</PageLink></div><PageHeading title={`Trip detail · ${id}`} description={`${trip.vehicle} · ${trip.driver} · Peliyagoda → ${trip.destination}`} actions={<Badge tone={incident&&!s.issueResolved?'danger':'info'}>{incident&&!s.issueResolved?'1 stop requires attention':trip.status==='Completed'?'Completed':'Route overview'}</Badge>}/><div className="dp-detail-grid"><Card><h2>Stop sequence</h2><p className="wp-description">Morning-run snapshot · {trip.total} stops</p><ol className="dp-timeline">{stops.map((name,i)=>{const label=i<trip.done?'Delivered':incident&&i===2&&!s.issueResolved?(s.issueStatus==='awaiting'?'Awaiting outcome':'Issue flagged'):incident&&i===2&&s.issueResolved?'Awaiting driver update':'Pending';return <li key={name} className={label==='Issue flagged'?'dp-incident':''}><span className="dp-step">{i+1}</span><div><strong>{name}</strong><p className="dp-muted">{i<trip.done?'Delivery recorded':`Planned stop ${i+1}`}</p>{incident&&i===2&&<p className="wp-description">{s.issueResolved?`Dispatcher note: ${s.issueNote}`:'Driver note: Rear loading bay blocked by water line repairs. Waiting for dispatch instructions.'}</p>}</div><Badge tone={label==='Delivered'?'success':label==='Issue flagged'?'danger':'neutral'}>{label}</Badge></li>;})}</ol></Card>
    <Card>{incident?<IssueActions state={s} dispatch={dispatch}/>:<><h2>Delivery progress</h2><p className="wp-description">{trip.done} of {trip.total} stops delivered.</p><AlertBanner title={trip.status==='Delayed'?'Arrival delayed by 25 minutes':'No open issues'}>{trip.status==='Delayed'?'Review the next arrival with the driver. This demo does not send messages.':'No dispatcher action is required for this run.'}</AlertBanner></>}</Card></div></>;

}
